name: Build pages

on:
  push:
    branches:
      - main
jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
          submodules: true
      - name: Install nix
        uses: cachix/install-nix-action@7be5dee1421f63d07e71ce6e0a9f8a4b07c2a487 # v31.6.1
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz
          extra_nix_config: |
            experimental-features = nix-command flakes pipe-operators
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix build .?submodules=1#default
      - run: |
          cp -rL result ./dist
          chmod -R u+rwX ./dist
      - name: Upload dist as pages-artifact
        id: deployment
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: dist/
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    timeout-minutes: 30
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
